#!/bin/bash

#**************************************************************************************************
# Author: Tida Sooreechine
# Date: 3/14/2017
# Program: CS344 Program 4 - OTP (One-Time Pad)
#**************************************************************************************************/

gcc keygen.c -o keygen
gcc otp_enc_d.c -o otp_enc_d
gcc otp_enc.c -o otp_enc 
gcc otp_dec_d.c -o otp_dec_d
gcc otp_dec.c -o otp_dec

